### ISSUE TITLE
API changes no longer allow this database cluster config to build

### ISSUE THREAD

**Issue by jameswjr** [ziedbentahar/strapi-on-aws-with-cdk#1]
I tried your repo and I noticed that some changes to deprecated parts of the API no longer permit the specification of the database to work just like this (using "InstanceProps").  The fix is to specify a writer and not to specify instances. Legacy instance props can be used.

**Comment by ziedbentahar** [comment]
Hi James,
Thanks for raising this ! Indeed that api is deprecated, I will update the
sample (and the article) in order to use the correct cdk definition for the
aurora v2 db.

**Comment by jameswjr** [comment]
Awesome! I have sample code I can share showing how I got it to work, but I'm fighting through a separate issue so I haven't quite completed a full build of the stack yet, so it's not quite end-to-end tested.  But I'll be happy to open a PR with changes if you like.

**Comment by ziedbentahar** [comment]
Awesome, of course you can open a PR, I will gladly merge it 😃

Thank you James !

**Comment by ziedbentahar** [comment]
Hi I have just made an update: 

- Updating the CDK version
- Using the new DatabaseCluster definition when creating Aurora Serverless V2
